
ServerEvents.recipes(event => {
  event.remove({ output: [


    // LIBRARIAN: librarian
    'patchouli:guide_book',
    'tide:fishing_journal',
    'archers:archer_spell_book',
    'paladins:priest_spell_book',
    'paladins:paladin_spell_book',
    'rogues:rogue_spell_book',
    'rogues:warrior_spell_book',
    'wizards:arcane_spell_book',
    'wizards:fire_spell_book',
    'wizards:frost_spell_book',
    'death_knights:blood_spell_book',
    'death_knights:unholy_spell_book',
    'death_knights:frost_spell_book',
    'xercapaint:item_canvas',
    'xercapaint:item_canvas_long',
    'xercapaint:item_canvas_tall',
    'xercapaint:item_canvas_large',
    'xercapaint:item_easel',

    // GRANDMASTER: "minecraft:librarian" (taiga) — chess theme (game piece moved
    //   off librarian) + chess_board_knight plate + chess_board_knight polearm
    'chessmod:chess_piece',
    'fantasy_armor:chess_board_knight_helmet',
    'fantasy_armor:chess_board_knight_chestplate',
    'fantasy_armor:chess_board_knight_leggings',
    'fantasy_armor:chess_board_knight_boots',
    'fantasy_weapons:weapon_chess_board_knight_polearm',


    // BISHOP: "paladins:monk" — paladin/crusader plate + armoroftheages holy armor (top-tier, buffed) + holy staves (moved from priest). [file: bishop.txt; priest wands/robes moved to PRIEST]
    'paladins:paladin_armor_head',
    'paladins:paladin_armor_chest',
    'paladins:paladin_armor_legs',
    'paladins:paladin_armor_feet',
    'paladins:crusader_armor_head',
    'paladins:crusader_armor_chest',
    'paladins:crusader_armor_legs',
    'paladins:crusader_armor_feet',
    'armoroftheages:holy_armor_head',
    'armoroftheages:holy_armor_chest',
    'armoroftheages:holy_armor_legs',
    'armoroftheages:holy_armor_feet',
    'paladins:holy_staff',
    'paladins:diamond_holy_staff',

    // PRIEST: "morevillagers:enderian" — wands + priest/prior robes + magnum torches (staves moved to bishop) [file: priest.txt; formerly "monk"]
    // (Mystic trader retired; torches folded in here as a "wardkeeper monk" theme.)
    'paladins:acolyte_wand',
    'paladins:holy_wand',
    'paladins:diamond_holy_wand',
    'paladins:priest_robe_head',
    'paladins:priest_robe_chest',
    'paladins:priest_robe_legs',
    'paladins:priest_robe_feet',
    'paladins:prior_robe_head',
    'paladins:prior_robe_chest',
    'paladins:prior_robe_legs',
    'paladins:prior_robe_feet',
    'magnumtorch:diamond_magnum_torch',
    'magnumtorch:emerald_magnum_torch',
    'magnumtorch:amethyst_magnum_torch',


    

    // ARCHER: "archers:archery_artisan"
    'archers:composite_longbow',
    'archers:crystal_longbow',
    'archers:crystal_shortbow',
    'archers:mechanic_shortbow',
    'archers:royal_longbow',
    'archers:heavy_crossbow',
    'archers:rapid_crossbow',
    'archers:flint_spear',
    'archers:iron_spear',
    'archers:golden_spear',
    'archers:diamond_spear',
    'archers:aeternium_spear',
    'archers:auto_fire_hook',
    'archers:archer_armor_head',
    'archers:archer_armor_chest',
    'archers:archer_armor_legs',
    'archers:archer_armor_feet',
    'archers:ranger_armor_head',
    'archers:ranger_armor_chest',
    'archers:ranger_armor_legs',
    'archers:ranger_armor_feet',
    'supplementaries:quiver',
    

    // MUSICIAN: cleric
    'immersive_melodies:ender_bass',
    'immersive_melodies:lute',
    'immersive_melodies:piano',
    'immersive_melodies:bagpipe',
    'immersive_melodies:flute',
    'immersive_melodies:handpan',
    'immersive_melodies:triangle',
    'immersive_melodies:tiny_drum',
    'immersive_melodies:trumpet',
    'immersive_melodies:vielle',
    'immersive_melodies:didgeridoo',
    // 'ribbits:maraca',

    // FLAG MAKER: 'minecraft:shepherd' — ONLY the 6 custom/themed minecells flags
    //   (sanctioned minecells exception: decorative-only). All 32 generic colored
    //   ribbon flags (small + large) + flag_pole stay normally craftable.
    'minecells:kings_crest_flag',
    'minecells:torn_kings_crest_flag',
    'minecells:black_bridge_flag',
    'minecells:insufferable_crypt_flag',
    'minecells:promenade_of_the_condemned_flag',
    'minecells:ramparts_flag',

    // BANKER
    'numismatics:red_card',
    'numismatics:red_id_card',
    'numismatics:white_card',
    'numismatics:white_id_card',
    'numismatics:orange_card',
    'numismatics:orange_id_card',
    'numismatics:magenta_card',
    'numismatics:magenta_id_card',
    'numismatics:light_blue_card',
    'numismatics:light_blue_id_card',
    'numismatics:yellow_card',
    'numismatics:yellow_id_card',
    'numismatics:lime_card',
    'numismatics:lime_id_card',
    'numismatics:pink_card',
    'numismatics:pink_id_card',
    'numismatics:gray_card',
    'numismatics:gray_id_card',
    'numismatics:light_gray_card',
    'numismatics:light_gray_id_card',
    'numismatics:cyan_card',
    'numismatics:cyan_id_card',
    'numismatics:purple_card',
    'numismatics:purple_id_card',
    'numismatics:blue_card',
    'numismatics:blue_id_card',
    'numismatics:brown_card',
    'numismatics:brown_id_card',
    'numismatics:green_card',
    'numismatics:green_id_card',
    'numismatics:red_card',
    'numismatics:red_id_card',
    'numismatics:black_card',
    'numismatics:black_id_card',
    'numismatics:banking_guide',
    'numismatics:vendor',
    'numismatics:brass_depositor',
    'numismatics:andesite_depositor',
    'numismatics:bank_terminal',

    // FISHERMAN: "minecraft:fisherman" — Tide tackle + fish_satchel/display + bobbers.
    //   Maritime gadgets moved to TINKERER. White bobber + 17 specials are trader-only;
    //   the 15 colored bobbers' default recipes are removed and replaced by
    //   white_fishing_bobber + dye recipes in bobber_recipes.js.js.
    'tide:stone_fishing_rod',
    'tide:iron_fishing_rod',
    'tide:golden_fishing_rod',
    'tide:crystal_fishing_rod',
    'tide:diamond_fishing_rod',
    'tide:fishing_line',
    'tide:reinforced_line',
    'tide:braided_line',
    'tide:golden_line',
    'tide:fishing_hook',
    'tide:iron_fishing_hook',
    'tide:lavaproof_fishing_hook',
    'tide:void_fishing_hook',
    'tide:fish_satchel',
    'tide:fish_display',
    'tide:white_fishing_bobber',
    'tide:amethyst_fishing_bobber',
    'tide:apple_fishing_bobber',
    'tide:chorus_fishing_bobber',
    'tide:diamond_fishing_bobber',
    'tide:duck_fishing_bobber',
    'tide:echo_fishing_bobber',
    'tide:enchanted_golden_apple_fishing_bobber',
    'tide:feather_fishing_bobber',
    'tide:golden_fishing_bobber',
    'tide:golden_apple_fishing_bobber',
    'tide:grassy_fishing_bobber',
    'tide:heart_fishing_bobber',
    'tide:iron_fishing_bobber',
    'tide:lichen_fishing_bobber',
    'tide:nautilus_fishing_bobber',
    'tide:netherite_fishing_bobber',
    'tide:pearl_fishing_bobber',
    // 15 colored bobbers — default slime+planks+dye recipe removed; remade as white+dye
    'tide:black_fishing_bobber',
    'tide:blue_fishing_bobber',
    'tide:brown_fishing_bobber',
    'tide:cyan_fishing_bobber',
    'tide:gray_fishing_bobber',
    'tide:green_fishing_bobber',
    'tide:light_blue_fishing_bobber',
    'tide:light_gray_fishing_bobber',
    'tide:lime_fishing_bobber',
    'tide:magenta_fishing_bobber',
    'tide:orange_fishing_bobber',
    'tide:pink_fishing_bobber',
    'tide:purple_fishing_bobber',
    'tide:red_fishing_bobber',
    'tide:yellow_fishing_bobber',

    // ENGINEER: "morevillagers:engineer" — ALL Immersive Aircraft components (structural,
    //   engines, gyro, + weapon/upgrade parts). Vehicles (biplane/airship/gyrodyne/
    //   quadrocopter/cargo_airship/warship/bamboo_hopper) are player-assembled, never sold.
    'immersive_aircraft:propeller',
    'immersive_aircraft:enhanced_propeller',
    'immersive_aircraft:industrial_gears',
    'immersive_aircraft:sturdy_pipes',
    'immersive_aircraft:improved_landing_gear',
    'immersive_aircraft:sail',
    'immersive_aircraft:hull',
    'immersive_aircraft:hull_reinforcement',
    'immersive_aircraft:boiler',
    'immersive_aircraft:steel_boiler',
    'immersive_aircraft:engine',
    'immersive_aircraft:eco_engine',
    'immersive_aircraft:nether_engine',
    'immersive_aircraft:gyroscope',
    'immersive_aircraft:gyroscope_hud',
    'immersive_aircraft:gyroscope_dials',
    'immersive_aircraft:rotary_cannon',
    'immersive_aircraft:bomb_bay',
    'immersive_aircraft:heavy_crossbow',
    'immersive_aircraft:telescope',

    // MECHANIST: "morevillagers:miner" — Create machines/tools + Create Additions
    //   electric tier (very expensive). mechanical_drill = most expensive trade in
    //   the pack. Trains (track_station/observer/signal) dropped → normally craftable.
    'create:wrench',
    'create:goggles',
    'create:schematic_table',
    'create:belt_connector',
    'create:empty_blaze_burner',
    'create:mechanical_saw',
    'create:deployer',
    'create:mechanical_arm',
    'create:mechanical_drill',
    'createaddition:electric_motor',
    'createaddition:alternator',
    'createaddition:connector',
    'createaddition:large_connector',
    'createaddition:redstone_relay',
    'createaddition:accumulator',
    'createaddition:capacitor',
    'createaddition:portable_energy_interface',
    'createaddition:tesla_coil',
    'createaddition:rolling_mill',

    // ENGINEER DISCIPLINES — class-gated (origins:recipe on cabacraft:eng_mechanical /
    //   eng_electrical / eng_aeronautical). Phase-3 removal-sync MISSED these base
    //   machines (the "rest were already removed by trader-audit" assumption was wrong
    //   for Engineer); exclusivity audit 2026-05-22 caught all 23. No trader fallback —
    //   Engineer is the sole gateway to Create (user-confirmed). Sibling Create/CA items
    //   are already locked in the MECHANIST block above.
    // -- Mechanical (Create) --
    'create:basin',
    'create:clutch',
    'create:depot',
    'create:encased_fan',
    'create:gearbox',
    'create:gearshift',
    'create:hand_crank',
    'create:mechanical_mixer',
    'create:mechanical_piston',
    'create:mechanical_press',
    'create:millstone',
    'create:water_wheel',
    // -- Electrical (Create Addition) --
    'createaddition:barbed_wire',
    'createaddition:copper_spool',
    'createaddition:digital_adapter',
    'createaddition:electrum_spool',
    'createaddition:gold_spool',
    'createaddition:modular_accumulator',
    'createaddition:small_light_connector',
    // -- Aeronautical (Immersive Machinery) --
    'immersive_machinery:bamboo_bee',
    'immersive_machinery:copperfin',
    'immersive_machinery:iron_drill',
    'immersive_machinery:tunnel_digger',


    // CULTIST 'villagersplus:occultist' — initiate death-knight gear + fantasy_armor dark_lord set + dark_lord_sword twin
    'fantasy_weapons:weapon_dark_lord_sword',
    'death_knights:initiate_armor_head',
    'death_knights:initiate_armor_chest',
    'death_knights:initiate_armor_legs',
    'death_knights:initiate_armor_feet',
    'fantasy_armor:dark_lord_helmet',
    'fantasy_armor:dark_lord_chestplate',
    'fantasy_armor:dark_lord_leggings',
    'fantasy_armor:dark_lord_boots',
    // 'jewelry:unique_attack_ring',
    // 'jewelry:unique_attack_necklace',
    // 'endrem:cryptic_eye
    // 'minecraft:end_crystal


    // SCIENTIST: 'villagersplus:alchemist' — plaguebringer gear + all infected fantasy_weapons
    'death_knights:plaguebringer_armor_head',
    'death_knights:plaguebringer_armor_chest',
    'death_knights:plaguebringer_armor_legs',
    'death_knights:plaguebringer_armor_feet',
    'death_knights:unholy_dk_ring',
    'death_knights:unholy_dk_necklace',
    'fantasy_weapons:weapon_infected_sharp_sword',
    'fantasy_weapons:weapon_infected_sharp_spear',
    'fantasy_weapons:weapon_infected_sharp_curved_sword',
    
    
    
    
    

    // BLIGHT: 'villagersplus:oceanographer' — crimson guard gear + blood/venom fantasy_weapons
    'death_knights:crimson_guard_armor_head',
    'death_knights:crimson_guard_armor_chest',
    'death_knights:crimson_guard_armor_legs',
    'death_knights:crimson_guard_armor_feet',
    'death_knights:blood_dk_ring',
    'death_knights:blood_dk_necklace',
    'fantasy_weapons:weapon_phantom_needle',
    'fantasy_weapons:weapon_rivers_of_blood',
    'fantasy_weapons:weapon_spider_fang',


    // FROST_KNIGHT: "minecraft:armorer" + type:"minecraft:taiga" (the "snow armorer")
    // Frost-themed armorer — armor, accessories, AND all DK runeblades/runeaxes,
    // plus fantasy_armor dark_cover. (The death_knight trader retired; blades folded in.)
    'death_knights:frozen_champion_armor_head',
    'death_knights:frozen_champion_armor_chest',
    'death_knights:frozen_champion_armor_legs',
    'death_knights:frozen_champion_armor_feet',
    'death_knights:frost_dk_ring',
    'death_knights:frost_dk_necklace',
    'fantasy_armor:dark_cover_helmet',
    'fantasy_armor:dark_cover_chestplate',
    'fantasy_armor:dark_cover_leggings',
    'fantasy_armor:dark_cover_boots',
    'death_knights:initiate_runeblade',
    'death_knights:iron_runeblade',
    'death_knights:diamond_runeblade',
    'death_knights:great_iron_runeblade',
    'death_knights:great_diamond_runeblade',
    'death_knights:great_iron_runeaxe',
    'death_knights:great_diamond_runeaxe',

    
    
    // NONE — class workbenches stay locked (class gear is bought, not crafted)
    'spell_engine:spell_binding',
    'paladins:monk_workbench',
    'rogues:arms_workbench',
    'archers:archers_workbench',
    // jewelry:jewelers_kit and runes:crafting_altar are CRAFTABLE — players make their own jewelry/runes

    // WIZARD: "wizards:wizard_merchant"
    'wizards:wand_novice',
    'wizards:wand_arcane',
    'wizards:wand_fire',
    'wizards:wand_frost',
    'wizards:staff_wizard',
    'wizards:staff_arcane',
    'wizards:staff_fire',
    'wizards:staff_frost',
    'wizards:wizard_robe_head',
    'wizards:wizard_robe_chest',
    'wizards:wizard_robe_legs',
    'wizards:wizard_robe_feet',
    'wizards:arcane_robe_head',
    'wizards:arcane_robe_chest',
    'wizards:arcane_robe_legs',
    'wizards:arcane_robe_feet',
    'wizards:fire_robe_head',
    'wizards:fire_robe_chest',
    'wizards:fire_robe_legs',
    'wizards:fire_robe_feet',
    'wizards:frost_robe_head',
    'wizards:frost_robe_chest',
    'wizards:frost_robe_legs',
    'wizards:frost_robe_feet',


    // ROGUE: "rogues:arms_merchant"
    'rogues:rogue_armor_head',
    'rogues:rogue_armor_chest',
    'rogues:rogue_armor_legs',
    'rogues:rogue_armor_feet',
    'rogues:assassin_armor_head',
    'rogues:assassin_armor_chest',
    'rogues:assassin_armor_legs',
    'rogues:assassin_armor_feet',
    // grave_sentinel fantasy plate + 2 standalone fantasy blades (moved from wanderer)
    'fantasy_armor:grave_sentinel_helmet',
    'fantasy_armor:grave_sentinel_chestplate',
    'fantasy_armor:grave_sentinel_leggings',
    'fantasy_armor:grave_sentinel_boots',
    'fantasy_weapons:weapon_cursed_blade',
    'fantasy_weapons:weapon_crimson_reaper',
    // (warrior/berserker armor moved to ARMORER below)
    // ARMS_MERCHANT: "rogues:arms_merchant" (desert) — all guns + gun accessories
    //   (moved off rogue; pistol also sold cheaper by pirate. Base guns + upgrade
    //   smithing template only — bayonet/scope muskets are player-smithed from these.)
    'musketmod:musket',
    'musketmod:blunderbuss',
    'musketmod:pistol',
    'musketmod:cartridge',
    'musketmod:musket_upgrade_smithing_template',

    // PIRATE: "morevillagers:oceanographer" — flintlock (musketmod:pistol, also sold
    //   by rogue but cheaper here), cutlass, lady_maria pirate plate, accents
    //   pirate_hat/captain_hat/bandolier/holstered_belt (accents covered by the
    //   blanket accents:sewing removal below; pistol covered by musketmod above)
    'fantasy_weapons:weapon_sharp_curved_sword',
    'fantasy_armor:lady_maria_helmet',
    'fantasy_armor:lady_maria_chestplate',
    'fantasy_armor:lady_maria_leggings',
    'fantasy_armor:lady_maria_boots',


    // BLACKSMITH: "minecraft:weaponsmith" — melee weapons only [file: blacksmith.txt;
    'paladins:iron_claymore',
    'paladins:iron_mace',
    'paladins:iron_great_hammer',
    'paladins:golden_claymore',
    'paladins:golden_mace',
    'paladins:golden_great_hammer',
    'paladins:diamond_claymore',
    'paladins:diamond_mace',
    'paladins:diamond_great_hammer',
    'rogues:iron_dagger',
    'rogues:iron_double_axe',
    'rogues:iron_glaive',
    'rogues:iron_sickle',
    'rogues:golden_dagger',
    'rogues:golden_double_axe',
    'rogues:golden_glaive',
    'rogues:golden_sickle',
    'rogues:diamond_dagger',
    'rogues:diamond_double_axe',
    'rogues:diamond_glaive',
    'rogues:diamond_sickle',
    //   formerly "bladesmith". paladins kite shields moved BACK to armorer.]

    // ARMORER: "minecraft:armorer" (plains) — forged plate + paladins kite shields.
    //   immersive_armors:heavy = "Heavy" (un-renamed); immersive_armors:warrior
    //   renamed "Viking" via item_names.js.js. fantasy_armor sets pulled out and
    //   parked in the TBD block just below (revisit later).
    'armoroftheages:iron_plate_armor_head',
    'armoroftheages:iron_plate_armor_chest',
    'armoroftheages:iron_plate_armor_legs',
    'armoroftheages:iron_plate_armor_feet',
    'immersive_armors:heavy_helmet',
    'immersive_armors:heavy_chestplate',
    'immersive_armors:heavy_leggings',
    'immersive_armors:heavy_boots',
    'immersive_armors:warrior_helmet',
    'immersive_armors:warrior_chestplate',
    'immersive_armors:warrior_leggings',
    'immersive_armors:warrior_boots',
    'rogues:warrior_armor_head',
    'rogues:warrior_armor_chest',
    'rogues:warrior_armor_legs',
    'rogues:warrior_armor_feet',
    'rogues:berserker_armor_head',
    'rogues:berserker_armor_chest',
    'rogues:berserker_armor_legs',
    'rogues:berserker_armor_feet',
    'paladins:iron_kite_shield',
    'paladins:golden_kite_shield',
    'paladins:diamond_kite_shield',
    // TBD — fantasy_armor sets pulled from armorer; still recipe-locked, not sold (revisit):
    'fantasy_armor:fog_guard_helmet',
    'fantasy_armor:fog_guard_chestplate',
    'fantasy_armor:fog_guard_leggings',
    'fantasy_armor:fog_guard_boots',
    'fantasy_armor:old_knight_helmet',
    'fantasy_armor:old_knight_chestplate',
    'fantasy_armor:old_knight_leggings',
    'fantasy_armor:old_knight_boots',
    'fantasy_armor:dragonslayer_helmet',
    'fantasy_armor:dragonslayer_chestplate',
    'fantasy_armor:dragonslayer_leggings',
    'fantasy_armor:dragonslayer_boots',
    'fantasy_armor:spark_of_dawn_helmet',
    'fantasy_armor:spark_of_dawn_chestplate',
    'fantasy_armor:spark_of_dawn_leggings',
    'fantasy_armor:spark_of_dawn_boots',
    // TBD — orphan twin weapons recipe-locked too, so each set travels with its blade
    //   in the fantasy_armor pass (dark_cover armor is sold on frost_knight; its sword
    //   stays parked until that pass decides):
    'fantasy_weapons:weapon_dragonslayer_halberd',
    'fantasy_weapons:weapon_fog_guard_sword',
    'fantasy_weapons:weapon_spark_of_dawn_polearm',
    'fantasy_weapons:weapon_dark_cover_sword',
    // TBD — relic_armorer RETIRED; these exotic fantasy_armor sets stay recipe-locked,
    //   not sold (revisit in the dedicated fantasy_armor pass with the other parked sets)
    'fantasy_armor:flesh_of_the_feaster_helmet',
    'fantasy_armor:flesh_of_the_feaster_chestplate',
    'fantasy_armor:flesh_of_the_feaster_leggings',
    'fantasy_armor:flesh_of_the_feaster_boots',
    'fantasy_armor:dead_gladiator_helmet',
    'fantasy_armor:dead_gladiator_chestplate',
    'fantasy_armor:dead_gladiator_leggings',
    'fantasy_armor:dead_gladiator_boots',
    'fantasy_armor:silver_knight_helmet',
    'fantasy_armor:silver_knight_chestplate',
    'fantasy_armor:silver_knight_leggings',
    'fantasy_armor:silver_knight_boots',
    'fantasy_armor:gilded_hunt_helmet',
    'fantasy_armor:gilded_hunt_chestplate',
    'fantasy_armor:gilded_hunt_leggings',
    'fantasy_armor:gilded_hunt_boots',

    // TBD — immersive_armors sets awaiting trader assignment (recipes removed; unobtainable until reassigned)
    'immersive_armors:wooden_helmet',
    'immersive_armors:wooden_chestplate',
    'immersive_armors:wooden_leggings',
    'immersive_armors:wooden_boots',
    'immersive_armors:bone_helmet',
    'immersive_armors:bone_chestplate',
    'immersive_armors:bone_leggings',
    'immersive_armors:bone_boots',
    'immersive_armors:robe_helmet',
    'immersive_armors:robe_chestplate',
    'immersive_armors:robe_leggings',
    'immersive_armors:robe_boots',
    'immersive_armors:slime_helmet',
    'immersive_armors:slime_chestplate',
    'immersive_armors:slime_leggings',
    'immersive_armors:slime_boots',
    'immersive_armors:prismarine_helmet',
    'immersive_armors:prismarine_chestplate',
    'immersive_armors:prismarine_leggings',
    'immersive_armors:prismarine_boots',
    'immersive_armors:steampunk_helmet',
    'immersive_armors:steampunk_chestplate',
    'immersive_armors:steampunk_leggings',
    'immersive_armors:steampunk_boots',
    // (immersive_armors:warrior moved to ARMORER block above — renamed "Viking")
    'immersive_armors:wither_helmet',
    'immersive_armors:wither_chestplate',
    'immersive_armors:wither_leggings',
    'immersive_armors:wither_boots',
    'immersive_armors:divine_helmet',
    'immersive_armors:divine_chestplate',
    'immersive_armors:divine_leggings',
    'immersive_armors:divine_boots',




    // TINKERER: "minecraft:toolsmith" — TECH gadgets only: Tide instruments, exposure
    //   camera kit, Supplementaries tech gadgets, create extendo_grip, immersive_machinery
    //   redstone (redstone_mechanism = most expensive tinkerer item).
    //   Dropped → now normally craftable: slingshot, flute, hourglass, bomb, bomb_spiky,
    //   turn_table, pulley_block. (supplementaries:speedometer is sold but has no recipe,
    //   so it's intentionally NOT listed here.)
    'tide:pocket_watch',
    'tide:depth_meter',
    'tide:climate_gauge',
    'tide:weather_radio',
    'tide:lunar_calendar',
    'create:extendo_grip',
    'slide_show:projector',
    'immersive_machinery:redstone_sheep',
    'immersive_machinery:redstone_mechanism',
    'supplementaries:rope_arrow',
    'supplementaries:spring_launcher',
    'supplementaries:altimeter',
    'supplementaries:wrench',
    'exposure:camera',
    'exposure:black_and_white_film',
    'exposure:color_film',

    // 'infinitybuttons:red_emergency_button',
    // 'infinitybuttons:red_safe_emergency_button',
    // 'infinitybuttons:bookshelf_secret_button',
    // 'infinitybuttons:brick_secret_button',
    // 'infinitybuttons:stone_brick_secret_button',
    // 'infinitybuttons:lantern_lever',
    // 'infinitybuttons:doorbell',
    // 'infinitybuttons:doorbell_button',
    // 'infinitybuttons:letter_button',

    // FISHER: Tide tackle — class-gated (origins:recipe on cabacraft:fisher)
    // BREWER: brewinandchewin — class-gated (origins:recipe on cabacraft:brewer)
    'brewinandchewin:beer',
    'brewinandchewin:beer_tankard',
    'brewinandchewin:bloody_mary',
    'brewinandchewin:bloody_mary_tankard',
    'brewinandchewin:cheesy_pasta',
    'brewinandchewin:cocoa_fudge',
    'brewinandchewin:creamy_onion_soup',
    'brewinandchewin:dread_nog',
    'brewinandchewin:dread_nog_tankard',
    'brewinandchewin:egg_grog',
    'brewinandchewin:egg_grog_tankard',
    'brewinandchewin:fermentation_controller',
    'brewinandchewin:fiery_fondue',
    'brewinandchewin:fiery_fondue_pot',
    'brewinandchewin:flaxen_cheese_wedge',
    'brewinandchewin:flaxen_cheese_wheel',
    'brewinandchewin:glittering_grenadine',
    'brewinandchewin:glittering_grenadine_tankard',
    'brewinandchewin:ham_and_cheese_sandwich',
    'brewinandchewin:horror_lasagna',
    'brewinandchewin:item_coaster',
    'brewinandchewin:jerky',
    'brewinandchewin:keg',
    'brewinandchewin:kimchi',
    'brewinandchewin:kippers',
    'brewinandchewin:kombucha',
    'brewinandchewin:kombucha_tankard',
    'brewinandchewin:mead',
    'brewinandchewin:mead_tankard',
    'brewinandchewin:pale_jane',
    'brewinandchewin:pale_jane_tankard',
    'brewinandchewin:pickled_pickles',
    'brewinandchewin:pizza',
    'brewinandchewin:pizza_slice',
    'brewinandchewin:quiche',
    'brewinandchewin:quiche_slice',
    'brewinandchewin:red_rum',
    'brewinandchewin:red_rum_tankard',
    'brewinandchewin:rice_wine',
    'brewinandchewin:rice_wine_tankard',
    'brewinandchewin:saccharine_rum',
    'brewinandchewin:saccharine_rum_tankard',
    'brewinandchewin:salty_folly',
    'brewinandchewin:salty_folly_tankard',
    'brewinandchewin:scarlet_cheese_wedge',
    'brewinandchewin:scarlet_cheese_wheel',
    'brewinandchewin:scarlet_pierogies',
    'brewinandchewin:steel_toe_stout',
    'brewinandchewin:steel_toe_stout_tankard',
    'brewinandchewin:strongroot_ale',
    'brewinandchewin:strongrot_ale_tankard',
    'brewinandchewin:tankard',
    'brewinandchewin:unripe_flaxen_cheese_wheel',
    'brewinandchewin:unripe_scarlet_cheese_wheel',
    'brewinandchewin:vegetable_omelet',
    'brewinandchewin:vodka',
    'brewinandchewin:vodka_tankard',
    'brewinandchewin:withering_dross',
    'brewinandchewin:withering_dross_tankard',
    // BARD: instruments/discs/chess/scribe — class-gated (origins:recipe on cabacraft:bard)
    'chessmod:board_block',
    'xercapaint:item_palette',
    'nirvana:music_disc_jam',
    // DECORATOR: wallpapers + themed flags — class-gated (origins:recipe on cabacraft:decorator)
    'wallpapers:acorn_wallpaper_roll_dma',
    'wallpapers:action_wallpaper_roll',
    'wallpapers:amber_wallpaper_roll',
    'wallpapers:amber_wallpaper_roll_dma',
    'wallpapers:aqua_wallpaper_roll',
    'wallpapers:artichoke_wallpaper_roll_dma',
    'wallpapers:ash_wallpaper_roll',
    'wallpapers:banana_wallpaper_roll_dma',
    'wallpapers:beige_wallpaper_roll',
    'wallpapers:black_wallpaper_roll',
    'wallpapers:blue_wallpaper_roll',
    'wallpapers:bricks_wallpaper_roll',
    'wallpapers:brown_wallpaper_roll',
    'wallpapers:cerulean_wallpaper_roll_dma',
    'wallpapers:clouds_wallpaper_roll',
    'wallpapers:coral_wallpaper_roll',
    'wallpapers:cozy_wallpaper_roll',
    'wallpapers:creeper_wallpaper_roll',
    'wallpapers:cyan_wallpaper_roll',
    'wallpapers:floral_wallpaper_roll',
    'wallpapers:forest_wallpaper_roll',
    'wallpapers:frosted_wallpaper_roll',
    'wallpapers:fuchsia_wallpaper_roll_dma',
    'wallpapers:ginger_wallpaper_roll',
    'wallpapers:grape_wallpaper_roll_dma',
    'wallpapers:gray_wallpaper_roll',
    'wallpapers:green_wallpaper_roll',
    'wallpapers:indigo_wallpaper_roll',
    'wallpapers:indigo_wallpaper_roll_dma',
    'wallpapers:light_blue_wallpaper_roll',
    'wallpapers:light_gray_wallpaper_roll',
    'wallpapers:lime_wallpaper_roll',
    'wallpapers:magenta_wallpaper_roll',
    'wallpapers:maroon_wallpaper_roll',
    'wallpapers:maroon_wallpaper_roll_dma',
    'wallpapers:mauve_wallpaper_roll_dma',
    'wallpapers:mint_wallpaper_roll',
    'wallpapers:mint_wallpaper_roll_dma',
    'wallpapers:mold_wallpaper_roll_dma',
    'wallpapers:navy_wallpaper_roll',
    'wallpapers:navy_wallpaper_roll_dma',
    'wallpapers:oasis_wallpaper_roll',
    'wallpapers:ocean_wallpaper_roll',
    'wallpapers:olive_wallpaper_roll',
    'wallpapers:orange_wallpaper_roll',
    'wallpapers:peach_wallpaper_roll_dma',
    'wallpapers:periwinkle_wallpaper_roll_dma',
    'wallpapers:pineapple_wallpaper_roll',
    'wallpapers:pink_wallpaper_roll',
    'wallpapers:primary_wallpaper_roll',
    'wallpapers:purple_wallpaper_roll',
    'wallpapers:red_wallpaper_roll',
    'wallpapers:rose_wallpaper_roll',
    'wallpapers:sage_wallpaper_roll_dma',
    'wallpapers:sap_wallpaper_roll_dma',
    'wallpapers:shamrock_wallpaper_roll_dma',
    'wallpapers:show_wallpaper_roll',
    'wallpapers:slate_wallpaper_roll',
    'wallpapers:stars_wallpaper_roll',
    'wallpapers:tan_wallpaper_roll',
    'wallpapers:teal_wallpaper_roll',
    'wallpapers:ultimate_wallpaper_roll',
    'wallpapers:ultra_ultimate_wallpaper_roll',
    'wallpapers:velvet_wallpaper_roll_dma',
    'wallpapers:verdant_wallpaper_roll',
    'wallpapers:vermilion_wallpaper_roll_dma',
    'wallpapers:white_wallpaper_roll',
    'wallpapers:wifi_wallpaper_roll',
    'wallpapers:yellow_wallpaper_roll',
    'wallpapers:andesite_skirting_board',
    'wallpapers:blackstone_skirting_board',
    'wallpapers:broken_quartz_skirting_board',
    'wallpapers:calcite_skirting_board',
    'wallpapers:dark_prismarine_skirting_board',
    'wallpapers:deepslate_skirting_board',
    'wallpapers:diorite_skirting_board',
    'wallpapers:dripstone_skirting_board',
    'wallpapers:gold_skirting_board',
    'wallpapers:granite_skirting_board',
    'wallpapers:prismarine_skirting_board',
    'wallpapers:quartz_skirting_board',
    'wallpapers:stone_skirting_board',
    'wallpapers:tuff_skirting_board',
    // HERBALIST: nirvana catalogue — class-gated (origins:recipe on cabacraft:herbalist)
    'nirvana:black_hemp_burlap',
    'nirvana:black_woven_burlap',
    'nirvana:bliss_bloom',
    'nirvana:blue_hemp_burlap',
    'nirvana:blue_woven_burlap',
    'nirvana:bong',
    'nirvana:brown_hemp_burlap',
    'nirvana:brown_woven_burlap',
    'nirvana:cyan_hemp_burlap',
    'nirvana:cyan_woven_burlap',
    'nirvana:deerstalker',
    'nirvana:gray_hemp_burlap',
    'nirvana:gray_woven_burlap',
    'nirvana:green_hemp_burlap',
    'nirvana:green_woven_burlap',
    'nirvana:hemp',
    'nirvana:hemp_burlap',
    'nirvana:hemp_cloth',
    'nirvana:hemp_crate',
    'nirvana:hemp_seeds',
    'nirvana:herbal_salve',
    'nirvana:joint',
    'nirvana:light_blue_hemp_burlap',
    'nirvana:light_blue_woven_burlap',
    'nirvana:light_gray_hemp_burlap',
    'nirvana:light_gray_woven_burlap',
    'nirvana:lime_hemp_burlap',
    'nirvana:lime_woven_burlap',
    'nirvana:magenta_hemp_burlap',
    'nirvana:magenta_woven_burlap',
    'nirvana:old_pipe',
    'nirvana:orange_hemp_burlap',
    'nirvana:orange_woven_burlap',
    'nirvana:peace_banner_pattern',
    'nirvana:pink_hemp_burlap',
    'nirvana:pink_woven_burlap',
    'nirvana:potion_bong',
    'nirvana:potted_wild_hemp',
    'nirvana:purple_hemp_burlap',
    'nirvana:purple_woven_burlap',
    'nirvana:red_hemp_burlap',
    'nirvana:red_woven_burlap',
    'nirvana:reefer_head',
    'nirvana:reefer_spawn_egg',
    'nirvana:stuffed_pipe',
    'nirvana:suspicious_pipe',
    'nirvana:thc',
    'nirvana:thc_minecart',
    'nirvana:weed',
    'nirvana:weed_brownie',
    'nirvana:weed_crate',
    'nirvana:white_hemp_burlap',
    'nirvana:white_woven_burlap',
    'nirvana:wild_hemp',
    'nirvana:woven_burlap',
    'nirvana:yellow_hemp_burlap',
    'nirvana:yellow_woven_burlap',

    //NONE
    "minecraft:shulker_box",
    "minecraft:white_shulker_box",
    "minecraft:orange_shulker_box",
    "minecraft:magenta_shulker_box",
    "minecraft:light_blue_shulker_box",
    "minecraft:yellow_shulker_box",
    "minecraft:lime_shulker_box",
    "minecraft:pink_shulker_box",
    "minecraft:gray_shulker_box",
    "minecraft:light_gray_shulker_box",
    "minecraft:cyan_shulker_box",
    "minecraft:purple_shulker_box",
    "minecraft:blue_shulker_box",
    "minecraft:brown_shulker_box",
    "minecraft:green_shulker_box",
    "minecraft:red_shulker_box",
    "minecraft:black_shulker_box",
    "morevillagers:oceanography_table",
    "morevillagers:woodworking_table",
    "morevillagers:decayed_workbench",
    "morevillagers:purpur_altar",
    "morevillagers:blueprint_table",
    "morevillagers:gardening_table",
    "morevillagers:hunting_post",
    "morevillagers:mining_bench",
    "villagersplus:alchemist_table",
    "villagersplus:alchemist_table",
    "minecells:prison_dimensional_rune",
    "minecells:promenade_dimensional_rune",
    "minecells:ramparts_dimensional_rune",
    "minecells:insufferable_dimensional_rune",
    "minecells:black_bridge_dimensional_rune",
    "minecells:prison_doorway",
    "minecells:promenade_doorway",
    "minecells:ramparts_doorway",
    "minecells:insufferable_crypt_doorway",
    "minecells:prison_doorway",
    "minecells:promenade_doorway",
    "minecells:ramparts_doorway",
    "minecells:black_bridge_doorway",

    // RONIN: "minecraft:weaponsmith" (taiga) — Eastern lamellar (AOTA do-maru/o-yoroi/raijin + bamboo hat) + fantasy ronin set + katana-family blades
    'armoroftheages:bamboo_hat',
    'fantasy_weapons:weapon_wakizashi',
    'fantasy_weapons:weapon_black_katana',
    'fantasy_weapons:weapon_nagakiba',
    'fantasy_weapons:weapon_marai_executioner_sword',
    'armoroftheages:japanese_light_armor_head',
    'armoroftheages:japanese_light_armor_chest',
    'armoroftheages:japanese_light_armor_legs',
    'armoroftheages:japanese_light_armor_feet',
    'armoroftheages:o_yoroi_armor_head',
    'armoroftheages:o_yoroi_armor_chest',
    'armoroftheages:o_yoroi_armor_legs',
    'armoroftheages:o_yoroi_armor_feet',
    'armoroftheages:raijin_armor_head',
    'armoroftheages:raijin_armor_chest',
    'armoroftheages:raijin_armor_legs',
    'armoroftheages:raijin_armor_feet',
    'fantasy_armor:ronin_helmet',
    'fantasy_armor:ronin_chestplate',
    'fantasy_armor:ronin_leggings',
    'fantasy_armor:ronin_boots',

    // NOMAD: "minecraft:armorer" (desert) — AOTA sun-gold (pharaoh/anubis/exalted_aurum/quetzalcoatl) + fantasy golden_horns/golden_execution + desert/gold weapons
    'fantasy_weapons:weapon_desert_wind',
    'fantasy_weapons:weapon_golden_halberd',
    'fantasy_weapons:weapon_marika_hammer',
    'fantasy_weapons:weapon_golden_horns_battleaxe',
    'fantasy_weapons:weapon_golden_execution_battleaxe',
    'fantasy_weapons:weapon_kingslayer',
    'armoroftheages:pharaoh_armor_head',
    'armoroftheages:pharaoh_armor_chest',
    'armoroftheages:pharaoh_armor_legs',
    'armoroftheages:pharaoh_armor_feet',
    'armoroftheages:anubis_armor_head',
    'armoroftheages:anubis_armor_chest',
    'armoroftheages:anubis_armor_legs',
    'armoroftheages:anubis_armor_feet',
    'armoroftheages:exalted_aurum_armor_head',
    'armoroftheages:exalted_aurum_armor_chest',
    'armoroftheages:exalted_aurum_armor_legs',
    'armoroftheages:exalted_aurum_armor_feet',
    'armoroftheages:quetzalcoatl_armor_head',
    'armoroftheages:quetzalcoatl_armor_chest',
    'armoroftheages:quetzalcoatl_armor_legs',
    'armoroftheages:quetzalcoatl_armor_feet',
    'fantasy_armor:golden_horns_helmet',
    'fantasy_armor:golden_horns_chestplate',
    'fantasy_armor:golden_horns_leggings',
    'fantasy_armor:golden_horns_boots',
    'fantasy_armor:golden_execution_helmet',
    'fantasy_armor:golden_execution_chestplate',
    'fantasy_armor:golden_execution_leggings',
    'fantasy_armor:golden_execution_boots',

    // TBD — boss-relic / champion-tier sets: recipe-locked, NOT yet sold by any
    //   trader (no "champion" trader — awaiting assignment per user). Distribute
    //   into ronin/nomad/centurion/wanderer (or elsewhere) when decided.
    'fantasy_weapons:weapon_fury_of_the_storm',
    'fantasy_weapons:weapon_hand_of_malenia',
    'fantasy_weapons:weapon_hero_claymore',
    'fantasy_weapons:weapon_sunset_wings_claymore',
    'fantasy_weapons:weapon_dragons_doom',
    'fantasy_weapons:weapon_fates_beacon',
    'fantasy_armor:malenia_helmet',
    'fantasy_armor:malenia_chestplate',
    'fantasy_armor:malenia_leggings',
    'fantasy_armor:malenia_boots',
    'fantasy_armor:hero_helmet',
    'fantasy_armor:hero_chestplate',
    'fantasy_armor:hero_leggings',
    'fantasy_armor:hero_boots',
    'fantasy_armor:ornstein_helmet',
    'fantasy_armor:ornstein_chestplate',
    'fantasy_armor:ornstein_leggings',
    'fantasy_armor:ornstein_boots',
    'fantasy_armor:crucible_knight_helmet',
    'fantasy_armor:crucible_knight_chestplate',
    'fantasy_armor:crucible_knight_leggings',
    'fantasy_armor:crucible_knight_boots',
    'fantasy_armor:redeemer_helmet',
    'fantasy_armor:redeemer_chestplate',
    'fantasy_armor:redeemer_leggings',
    'fantasy_armor:redeemer_boots',
    'fantasy_armor:twinned_helmet',
    'fantasy_armor:twinned_chestplate',
    'fantasy_armor:twinned_leggings',
    'fantasy_armor:twinned_boots',
    'fantasy_armor:sunset_wings_helmet',
    'fantasy_armor:sunset_wings_chestplate',
    'fantasy_armor:sunset_wings_leggings',
    'fantasy_armor:sunset_wings_boots',

    // CENTURION: "minecraft:armorer" (jungle) — AOTA centurion + fantasy eclipse_soldier + legion spears + weathered old/sharp/savage blades
    'fantasy_weapons:weapon_hefty_club',
    'fantasy_weapons:weapon_old_blade',
    'fantasy_weapons:weapon_old_broadsword',
    'fantasy_weapons:weapon_old_dagger',
    'fantasy_weapons:weapon_sharp_sword',
    'fantasy_weapons:weapon_savage_sword',
    'fantasy_weapons:weapon_sharp_spear',
    'fantasy_weapons:weapon_savage_spear',
    'fantasy_weapons:weapon_savage_hammer',
    'fantasy_weapons:weapon_eclipse_soldier_spear',
    'armoroftheages:centurion_armor_head',
    'armoroftheages:centurion_armor_chest',
    'armoroftheages:centurion_armor_legs',
    'armoroftheages:centurion_armor_feet',
    'fantasy_armor:eclipse_soldier_helmet',
    'fantasy_armor:eclipse_soldier_chestplate',
    'fantasy_armor:eclipse_soldier_leggings',
    'fantasy_armor:eclipse_soldier_boots',

    // WANDERER: "minecraft:weaponsmith" (jungle) — rogue road kits (thief/wandering_wizard/wind_worshipper/forgotten_trace/evening_ghost) + light blades
    //   (cursed_blade + crimson_reaper moved to ROGUE)
    'fantasy_weapons:weapon_savage_dagger',
    'fantasy_weapons:weapon_volcano_flame',
    'fantasy_weapons:weapon_thief_dagger',
    'fantasy_weapons:weapon_wandering_wizard_sword',
    'fantasy_weapons:weapon_forgotten_trace_spear',
    'fantasy_armor:thief_helmet',
    'fantasy_armor:thief_chestplate',
    'fantasy_armor:thief_leggings',
    'fantasy_armor:thief_boots',
    'fantasy_armor:wandering_wizard_helmet',
    'fantasy_armor:wandering_wizard_chestplate',
    'fantasy_armor:wandering_wizard_leggings',
    'fantasy_armor:wandering_wizard_boots',
    'fantasy_armor:wind_worshipper_helmet',
    'fantasy_armor:wind_worshipper_chestplate',
    'fantasy_armor:wind_worshipper_leggings',
    'fantasy_armor:wind_worshipper_boots',
    'fantasy_armor:forgotten_trace_helmet',
    'fantasy_armor:forgotten_trace_chestplate',
    'fantasy_armor:forgotten_trace_leggings',
    'fantasy_armor:forgotten_trace_boots',
    'fantasy_armor:evening_ghost_helmet',
    'fantasy_armor:evening_ghost_chestplate',
    'fantasy_armor:evening_ghost_leggings',
    'fantasy_armor:evening_ghost_boots',

  ]})
})

ServerEvents.recipes(event => {
    // Remove all recipes where the output is from a specific mod
    event.remove({ output: /infinitybuttons:.*/ })

    // ACCENTS (hatter / outfitter / curiosities traders):
    // Every cosmetic uses the custom recipe type "accents:sewing", so one line
    // strips all 28 sewing recipes. Sewing Kit + Sewing Station are normal
    // crafting recipes and are NOT affected.
    event.remove({ type: 'accents:sewing' })

    // Uncomment if you also want to remove the Sewing Station / Kit:
    // event.remove({ output: 'accents:sewing_station' })
    // event.remove({ output: 'accents:sewing_kit' })
})
